# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc.tradeapi.v1.reports import reports_service_pb2 as grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc/tradeapi/v1/reports/reports_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportsServiceStub(object):
    """Сервис для получения пользовательских отчетов.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccountReport = channel.unary_unary(
                '/grpc.tradeapi.v1.reports.ReportsService/CreateAccountReport',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.CreateAccountReportRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.CreateAccountReportResponse.FromString,
                _registered_method=True)
        self.GetAccountReportInfo = channel.unary_unary(
                '/grpc.tradeapi.v1.reports.ReportsService/GetAccountReportInfo',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.GetAccountReportInfoRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.GetAccountReportInfoResponse.FromString,
                _registered_method=True)
        self.SubscribeAccountReportInfo = channel.unary_stream(
                '/grpc.tradeapi.v1.reports.ReportsService/SubscribeAccountReportInfo',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.SubscribeAccountReportInfoRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.SubscribeAccountReportInfoResponse.FromString,
                _registered_method=True)


class ReportsServiceServicer(object):
    """Сервис для получения пользовательских отчетов.
    """

    def CreateAccountReport(self, request, context):
        """Запустить генерацию отчета по счету за период
        Пример HTTP запроса:
        POST /v1/report
        Authorization: <token>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountReportInfo(self, request, context):
        """Получение информации о результате генерации отчета по счету
        Пример HTTP запроса:
        GET /v1/report/01KBMPQ3CEZ4BBCVGBW5JS8S8Y/info
        Authorization: <token>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeAccountReportInfo(self, request, context):
        """Подписка на информацию о результатах генерации отчета по счету. Стрим метод
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccountReport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccountReport,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.CreateAccountReportRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.CreateAccountReportResponse.SerializeToString,
            ),
            'GetAccountReportInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountReportInfo,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.GetAccountReportInfoRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.GetAccountReportInfoResponse.SerializeToString,
            ),
            'SubscribeAccountReportInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeAccountReportInfo,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.SubscribeAccountReportInfoRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.SubscribeAccountReportInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.tradeapi.v1.reports.ReportsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.tradeapi.v1.reports.ReportsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportsService(object):
    """Сервис для получения пользовательских отчетов.
    """

    @staticmethod
    def CreateAccountReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.reports.ReportsService/CreateAccountReport',
            grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.CreateAccountReportRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.CreateAccountReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountReportInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.reports.ReportsService/GetAccountReportInfo',
            grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.GetAccountReportInfoRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.GetAccountReportInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeAccountReportInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc.tradeapi.v1.reports.ReportsService/SubscribeAccountReportInfo',
            grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.SubscribeAccountReportInfoRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_reports_dot_reports__service__pb2.SubscribeAccountReportInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
