# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc.tradeapi.v1.corporateactions import corporate_actions_service_pb2 as grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc/tradeapi/v1/corporateactions/corporate_actions_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CorporateActionsServiceStub(object):
    """Сервис предоставления информации по корпоративным действиям (дивиденды, сплиты)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFutureSplits = channel.unary_unary(
                '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetFutureSplits',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureSplitsRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureSplitsResponse.FromString,
                _registered_method=True)
        self.GetPastSplits = channel.unary_unary(
                '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetPastSplits',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastSplitsRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastSplitsResponse.FromString,
                _registered_method=True)
        self.GetFutureBondsEvents = channel.unary_unary(
                '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetFutureBondsEvents',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureBondsEventsRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureBondsEventsResponse.FromString,
                _registered_method=True)
        self.GetPastBondsEvents = channel.unary_unary(
                '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetPastBondsEvents',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastBondsEventsRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastBondsEventsResponse.FromString,
                _registered_method=True)
        self.GetFutureDividends = channel.unary_unary(
                '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetFutureDividends',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureDividendsRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureDividendsResponse.FromString,
                _registered_method=True)
        self.GetPastDividends = channel.unary_unary(
                '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetPastDividends',
                request_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastDividendsRequest.SerializeToString,
                response_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastDividendsResponse.FromString,
                _registered_method=True)


class CorporateActionsServiceServicer(object):
    """Сервис предоставления информации по корпоративным действиям (дивиденды, сплиты)
    """

    def GetFutureSplits(self, request, context):
        """Получить предстоящие события сплитов по инструменту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPastSplits(self, request, context):
        """Получить историю сплитов по инструменту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFutureBondsEvents(self, request, context):
        """Получить календарь будущих событий по облигациям
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPastBondsEvents(self, request, context):
        """Получить календарь исторических событий по облигациям
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFutureDividends(self, request, context):
        """Получить список предстоящих (будущих) дивидендных выплат по инструменту.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPastDividends(self, request, context):
        """Получить исторические данные по выплаченным дивидендам инструмента
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CorporateActionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFutureSplits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFutureSplits,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureSplitsRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureSplitsResponse.SerializeToString,
            ),
            'GetPastSplits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPastSplits,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastSplitsRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastSplitsResponse.SerializeToString,
            ),
            'GetFutureBondsEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFutureBondsEvents,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureBondsEventsRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureBondsEventsResponse.SerializeToString,
            ),
            'GetPastBondsEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPastBondsEvents,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastBondsEventsRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastBondsEventsResponse.SerializeToString,
            ),
            'GetFutureDividends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFutureDividends,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureDividendsRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureDividendsResponse.SerializeToString,
            ),
            'GetPastDividends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPastDividends,
                    request_deserializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastDividendsRequest.FromString,
                    response_serializer=grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastDividendsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.tradeapi.v1.corporateactions.CorporateActionsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.tradeapi.v1.corporateactions.CorporateActionsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CorporateActionsService(object):
    """Сервис предоставления информации по корпоративным действиям (дивиденды, сплиты)
    """

    @staticmethod
    def GetFutureSplits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetFutureSplits',
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureSplitsRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureSplitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPastSplits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetPastSplits',
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastSplitsRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastSplitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFutureBondsEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetFutureBondsEvents',
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureBondsEventsRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureBondsEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPastBondsEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetPastBondsEvents',
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastBondsEventsRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastBondsEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFutureDividends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetFutureDividends',
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureDividendsRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetFutureDividendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPastDividends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.tradeapi.v1.corporateactions.CorporateActionsService/GetPastDividends',
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastDividendsRequest.SerializeToString,
            grpc_dot_tradeapi_dot_v1_dot_corporateactions_dot_corporate__actions__service__pb2.GetPastDividendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
